version: "3.7"
services:
    postgres:
        container_name: gbshop-postgres
        image: postgres:14.0-alpine
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: shop
        volumes:
            - postgres-volume:/var/lib/postgresql/data/
        ports:
            - "5432:5432"

    cache:
        container_name: gbshop-cache
        image: memcached
        ports:
            - "11211:11211"
        entrypoint:
            - memcached
            - -m 64

volumes:
    postgres-volume: