version: "3.7"
services:
    postgres:
        container_name: postgres
        image: postgres:14.0-alpine
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: shop
        volumes:
            - postgres-volume:/var/lib/postgresql/data/
        ports:
            - "5432:5432"

volumes:
    postgres-volume: