# Generated by Django 3.2.9 on 2021-12-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_shopuserprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_avatar',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
